name: Build kasm_chromium_proxy Image

on:
  push:
    branches: [ main, master ]
    paths:
      - '**'
      - '!**/*.md'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '**'
      - '!**/*.md'
      - '.github/workflows/build.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-platform image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --push \
            --no-cache \
            --tag ghcr.io/cryptshoe/kasm_chromium_proxy:latest \
            .
