name: Build kasm_chromium_proxy Image

on:
  push:
    branches: [ main, master ]
    paths:
      - '**'
      - '!**/*.md'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '**'
      - '!**/*.md'
      - '.github/workflows/build.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Build the Docker image
        run: |
          docker build --no-cache . --tag ghcr.io/cryptshoe/kasm_chromium_proxy:latest
        
      - name: Log in to the Container registry
        run: docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ${{ env.REGISTRY }}
      
      - name: Push the image
        run: |
          docker push ghcr.io/cryptshoe/kasm_chromium_proxy:latest